modLoader="javafml"
loaderVersion="[46,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="cooperativeadvancements"
version="${file.jarVersion}"
displayName="Cooperative Advancements"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/352568"
logoFile="icon.png"
authors="Grend"
description='''A simple mod to share advancements between all players on a server.'''

[[dependencies.cooperativeadvancements]]
	modId="forge"
	mandatory=true
	versionRange="[46,)"
	ordering="NONE"
	side="SERVER"

[[dependencies.cooperativeadvancements]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20,)"
	ordering="NONE"
	side="SERVER"